import { 
  PaperSizeKey, 
  PaperDimension, 
  IdPresetKey, 
  IdPreset, 
  PrintPackagePreset,
  AttireTemplate 
} from '@/types/studio'

export const PAPER_DIMENSIONS: Record<PaperSizeKey, PaperDimension> = {
  'A4': {
    name: 'A4 Paper',
    widthInches: 8.27,
    heightInches: 11.69,
    widthMm: 210,
    heightMm: 297,
    description: '210 × 297 mm • Most popular standard in PH',
  },
  'Letter': {
    name: 'Short / Letter',
    widthInches: 8.5,
    heightInches: 11.0,
    widthMm: 215.9,
    heightMm: 279.4,
    description: '8.5 × 11 in • Standard short bond paper',
  },
  'Folio': {
    name: 'Long / Folio',
    widthInches: 8.5,
    heightInches: 13.0,
    widthMm: 215.9,
    heightMm: 330.2,
    description: '8.5 × 13 in • Philippine standard long bond',
  },
  'Legal': {
    name: 'US Legal',
    widthInches: 8.5,
    heightInches: 14.0,
    widthMm: 215.9,
    heightMm: 355.6,
    description: '8.5 × 14 in • US Legal size',
  },
  '4R': {
    name: '4R Photo Paper',
    widthInches: 4.0,
    heightInches: 6.0,
    widthMm: 101.6,
    heightMm: 152.4,
    description: '4 × 6 in • Standard glossy photo paper',
  },
  '5R': {
    name: '5R Photo Paper',
    widthInches: 5.0,
    heightInches: 7.0,
    widthMm: 127.0,
    heightMm: 177.8,
    description: '5 × 7 in • Medium photo size',
  },
  'A3': {
    name: 'A3 Poster Paper',
    widthInches: 11.69,
    heightInches: 16.54,
    widthMm: 297,
    heightMm: 420,
    description: '297 × 420 mm • Large format sheet',
  },
}

export const ID_PRESETS: Record<IdPresetKey, IdPreset> = {
  '1x1': {
    id: '1x1',
    name: '1x1 ID Picture',
    widthInches: 1.0,
    heightInches: 1.0,
    widthMm: 25.4,
    heightMm: 25.4,
    aspectRatio: 1.0,
    description: '25.4 × 25.4 mm • School & Job applications',
    badge: 'Popular',
  },
  '2x2': {
    id: '2x2',
    name: '2x2 ID Picture',
    widthInches: 2.0,
    heightInches: 2.0,
    widthMm: 50.8,
    heightMm: 50.8,
    aspectRatio: 1.0,
    description: '50.8 × 50.8 mm • US Visa, NBI, Clearance',
    badge: 'Standard',
  },
  'passport_ph': {
    id: 'passport_ph',
    name: 'Philippine Passport (DFA)',
    widthInches: 1.378,
    heightInches: 1.772,
    widthMm: 35.0,
    heightMm: 45.0,
    aspectRatio: 35 / 45,
    description: '35 × 45 mm • Royal blue / White background',
    badge: 'Official',
  },
  'prc_csc': {
    id: 'prc_csc',
    name: 'PRC & CSC Standard',
    widthInches: 1.5,
    heightInches: 1.5,
    widthMm: 38.1,
    heightMm: 38.1,
    aspectRatio: 1.0,
    description: '1.5 × 1.5 in • With full nametag overlay',
    badge: 'Gov',
  },
  'wallet': {
    id: 'wallet',
    name: 'Wallet Size',
    widthInches: 2.5,
    heightInches: 3.5,
    widthMm: 63.5,
    heightMm: 88.9,
    aspectRatio: 2.5 / 3.5,
    description: '2.5 × 3.5 in • Keepsake & portrait',
  },
  '3R': {
    id: '3R',
    name: '3R Photo',
    widthInches: 3.5,
    heightInches: 5.0,
    widthMm: 88.9,
    heightMm: 127.0,
    aspectRatio: 3.5 / 5.0,
    description: '3.5 × 5 in • Small photo print',
  },
  '4R': {
    id: '4R',
    name: '4R Photo',
    widthInches: 4.0,
    heightInches: 6.0,
    widthMm: 101.6,
    heightMm: 152.4,
    aspectRatio: 4.0 / 6.0,
    description: '4 × 6 in • Standard album print',
  },
  '5R': {
    id: '5R',
    name: '5R Photo',
    widthInches: 5.0,
    heightInches: 7.0,
    widthMm: 127.0,
    heightMm: 177.8,
    aspectRatio: 5.0 / 7.0,
    description: '5 × 7 in • Medium frame print',
  },
  'custom': {
    id: 'custom',
    name: 'Custom Dimensions',
    widthInches: 2.0,
    heightInches: 2.0,
    widthMm: 50.8,
    heightMm: 50.8,
    aspectRatio: 1.0,
    description: 'Specify custom width & height',
  },
}

export const BACKDROP_COLORS = [
  { id: 'transparent', name: 'Transparent (PNG)', value: 'transparent', hex: 'transparent' },
  { id: 'white', name: 'Pure White (Standard ID / CSC)', value: '#FFFFFF', hex: '#FFFFFF' },
  { id: 'passport-blue', name: 'Studio Royal Blue (DFA / PRC)', value: '#0072CE', hex: '#0072CE' },
  { id: 'sky-blue', name: 'Soft Sky Blue (School ID)', value: '#2B90D9', hex: '#2B90D9' },
  { id: 'red', name: 'Classic Red (Visa / Red Cross)', value: '#D32F2F', hex: '#D32F2F' },
  { id: 'green', name: 'Green Screen (Chroma)', value: '#00E676', hex: '#00E676' },
  { id: 'studio-gray', name: 'Studio Neutral Gray', value: '#E2E8F0', hex: '#E2E8F0' },
  { id: 'dark-gray', name: 'Dark Slate Studio', value: '#1E293B', hex: '#1E293B' },
]

export const PRINT_PACKAGES: PrintPackagePreset[] = [
  {
    id: 'pkg_csc_job',
    name: 'Package A: CSC & Job Hunting Combo',
    description: '4 pcs 2x2 + 8 pcs 1x1 — Perfect for job applications',
    recommendedPaper: '4R',
    items: [
      { presetKey: '2x2', quantity: 4 },
      { presetKey: '1x1', quantity: 8 },
    ],
  },
  {
    id: 'pkg_all_1x1',
    name: 'Package B: All 1x1 Sheet',
    description: 'Maximized 1x1 ID copies (12 pcs on 4R, 24 pcs on A4)',
    recommendedPaper: '4R',
    items: [
      { presetKey: '1x1', quantity: 12 },
    ],
  },
  {
    id: 'pkg_all_2x2',
    name: 'Package C: All 2x2 Sheet',
    description: 'Maximized 2x2 ID copies (6 pcs on 4R, 12 pcs on A4)',
    recommendedPaper: '4R',
    items: [
      { presetKey: '2x2', quantity: 6 },
    ],
  },
  {
    id: 'pkg_passport_pack',
    name: 'Package D: DFA Passport & 1x1 Pack',
    description: '6 pcs Philippine Passport (35x45mm) + 4 pcs 1x1',
    recommendedPaper: '4R',
    items: [
      { presetKey: 'passport_ph', quantity: 6 },
      { presetKey: '1x1', quantity: 4 },
    ],
  },
  {
    id: 'pkg_universal_deluxe',
    name: 'Package E: Universal Mega Combo',
    description: '4 pcs 2x2 + 4 pcs Passport + 8 pcs 1x1 + 2 pcs Wallet',
    recommendedPaper: 'A4',
    items: [
      { presetKey: '2x2', quantity: 4 },
      { presetKey: 'passport_ph', quantity: 4 },
      { presetKey: '1x1', quantity: 8 },
      { presetKey: 'wallet', quantity: 2 },
    ],
  },
]

export const ATTIRE_TEMPLATES: AttireTemplate[] = [
  {
    id: 'barong_mens',
    name: 'Barong Tagalog (Men)',
    category: 'men',
    description: 'Philippine formal embroidered Barong',
    svgPath: '/assets/attire/barong-tagalog.svg',
  },
  {
    id: 'suit_mens_black',
    name: 'Business Suit & Tie (Men)',
    category: 'men',
    description: 'Black blazer, white shirt with dark tie',
    svgPath: '/assets/attire/mens-suit.svg',
  },
  {
    id: 'blazer_womens_black',
    name: 'Formal Blazer (Women)',
    category: 'women',
    description: 'Navy blazer with inner white blouse',
    svgPath: '/assets/attire/womens-blazer.svg',
  },
  {
    id: 'polo_collared_white',
    name: 'White Collared Polo (Unisex)',
    category: 'unisex',
    description: 'Clean white collared shirt for school & government',
    svgPath: '/assets/attire/collared-polo.svg',
  },
]
