'use client'

import { useEffect } from 'react'

export function PrintReceiptClient({ order }: { order: any }) {
  useEffect(() => {
    // Automatically trigger print dialog when component mounts
    setTimeout(() => {
      window.print()
    }, 500)
  }, [])

  const items = order.order_items || []
  const isPaid = order.payment_status === 'paid'

  return (
    <div className="min-h-screen bg-white text-black p-8 font-mono print:p-0">
      <div className="max-w-md mx-auto bg-white border border-gray-200 p-8 shadow-sm print:border-none print:shadow-none">
        
        {/* Header */}
        <div className="text-center mb-6">
          <h1 className="text-2xl font-bold uppercase tracking-widest">{order.shops.name}</h1>
          <p className="text-sm mt-1">Order #{order.order_number || order.id.split('-')[0]}</p>
          <p className="text-xs mt-1">{new Date(order.created_at).toLocaleString()}</p>
        </div>

        <div className="border-t border-b border-dashed border-gray-300 py-4 mb-6">
          <div className="flex justify-between text-sm mb-1">
            <span className="font-semibold">Customer:</span>
            <span>{order.customer_name}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="font-semibold">Contact:</span>
            <span>{order.customer_contact || 'N/A'}</span>
          </div>
        </div>

        {/* Items */}
        <div className="mb-6">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-300">
                <th className="text-left pb-2">Item</th>
                <th className="text-right pb-2">Qty</th>
                <th className="text-right pb-2">Price</th>
              </tr>
            </thead>
            <tbody>
              {items.map((item: any) => (
                <tr key={item.id} className="border-b border-gray-100">
                  <td className="py-2 pr-2">
                    <div className="font-medium">{item.presets?.name || 'Custom'}</div>
                    <div className="text-xs text-gray-500">{item.presets?.paper_type}</div>
                  </td>
                  <td className="py-2 text-right align-top">{item.quantity}</td>
                  <td className="py-2 text-right align-top">₱{Number(item.subtotal).toLocaleString('en-US', {minimumFractionDigits: 2})}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="border-t border-gray-300 pt-4 mb-8 space-y-2">
          {order.is_rush && (
            <div className="flex justify-between text-sm text-red-600 font-bold uppercase">
              <span>Rush Fee Applied</span>
            </div>
          )}
          <div className="flex justify-between text-lg font-bold">
            <span>TOTAL</span>
            <span>₱{Number(order.total_amount).toLocaleString('en-US', {minimumFractionDigits: 2})}</span>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center">
          <div className={`inline-block px-4 py-1 border-2 font-bold uppercase tracking-widest text-lg mb-4 ${isPaid ? 'border-green-600 text-green-600' : 'border-red-600 text-red-600'}`}>
            {isPaid ? 'PAID' : 'UNPAID'}
          </div>
          <p className="text-xs text-gray-500">Thank you for your business!</p>
          <p className="text-xs text-gray-400 mt-1">Generated by Prynt</p>
        </div>

      </div>
    </div>
  )
}
